strings = ["Why don't scientists trust atoms? Because they make up everything!",
           "Why was the math book sad? Because it had too many problems!",
           "Why did the tomato turn red? Because it saw the salad dressing!",
           "Why did the cookie go to the doctor? Because it felt crumbly!",
           "Why did the computer cold? Because it left its Windows open!",
           "Why did the scarecrow win an award? Because he was outstanding in his field!",
           "Why did the hipster burn his tongue? He drank his coffee before it was cool!",
           "Why did the frog call his insurance company? He had a jump in his car!",
           "Why did the bicycle fall over? Because it was two-tired!",
           "Why did the chicken cross the playground? To get to the other slide!",
           "Why did the shark cross the ocean? To get to the other tide!",
           "Why did the ghost go to the bar? For a booze cruise!", 
           "Why did the duck go to therapy? He was feeling down!",
           "Why did the math book look so mad? Because it had too many problems!",
           "Why did the elephant wear red suspenders? To keep his pants up!",
           "Why did the football team go to the bank? To get their quarterback!",
           "Why did the skeleton go to the party? He wanted to dance!",
           "Why did the owl go to the doctor? Because he felt hoot-less!",
           "Why did the monkey put a piece of paper over his head? He wanted to be a snowflake!",
           "Why did the snake go to school? To learn his hiss-tory!"]
